solarus-games/solarus

src/EntityData.cpp
src/MapData.cpp
src/QuestResources.cpp
src/SpriteAnimationSet.cpp
src/SpriteData.cpp
src/entities/Tileset.cpp
src/entities/TilesetData.cpp
src/lowlevel/FontResource.cpp
src/lua/EntityApi.cpp

I removed a bunch of `map::insert` in the code and replaced them with `map::emplace` which allows to drop the call to `std::make_pair`. It might even be slightly more efficient, but before all, it allows for terser code.

Less map::insert, more map::emplace instead.

---

include/solarus/lowlevel/Random.h
src/lowlevel/Random.cpp

I changed the random number generation engine so that it uses the new C++11 `<random>` instead of the old `std::rand`. You can find many articles on the internet about the problems of `std::rand`, like its lack of thread-safety and more than anything else, the lack of guarantees for a standard-compliant function. Even the C11 standard has a note telling that it is not inherently safe. On the other hand, the C++11 `<random>` API is safe and more flexible. The only thing I couldn't do was to use `std::random_device` (which generates non-deterministic random numbers) since some platforms such as MinGW actually always produce the same sequence of numbers.
If needed, we can also create a function to create pseudo-random floating-points number with any distribution we want.

Changed to safer modern random engine.

---

src/lua/LuaTools.cpp

Use the standard functions from `<cctype>` instead of manually recomputing them. Some additional details, even though they are rather irrelevant:
* It may be a little bit slower since the functions from `<cctype>` have to be locale-aware, but not enough to be noticed.
* The standard only guarantees that the characters `'0' .. '9'` are contiguous. Actually, if the character set was EBCDIC instead of ASCII, the checks for the alphabetical characters would have failed. It shouldn't matter anyway since almost everything is ASCII-based nowadays.

Use the standard functions from cctype.

---

include/solarus/lowlevel/Color.h
include/solarus/lowlevel/Color.inl
include/solarus/lowlevel/Point.h
include/solarus/lowlevel/Point.inl
include/solarus/lowlevel/Rectangle.h
include/solarus/lowlevel/Rectangle.inl
include/solarus/lowlevel/Size.h
include/solarus/lowlevel/Size.inl

I saw that you made `Rectangle` and `Color`'s constructors `constexpr`. These classes might have well have their simple getters `constexpr` then, it doesn't cost anything. This one patch should be harmless (sorry again for the previous one -__-); the game still compiles and runs fine.

More constexpr in Rectangle and Color.

---

include/solarus/lowlevel/Point.h
include/solarus/lowlevel/Point.inl
include/solarus/lowlevel/Size.h
include/solarus/lowlevel/Size.inl

I played the consistency card and made all the functions in `Point` and `Size` take `const&` parameters and made them `constexpr` whenever possible. As aways, I doubt that it will incur any performance loss/gain, but it will make the code more consistent overall.

More constexpr and consistency in Point and Size.

---

include/solarus/lowlevel/Geometry.h
src/lowlevel/Geometry.cpp
src/movements/StraightMovement.cpp

`Geometry::get_angle` already performed operations with `double` values but took `int` parameters (as you said, probablu because it was only ever given integers at some point). I changed it to take `double` parameters instead.
The only notable difference is that `StraightMovement` doesn't have to cast its `double` values to `int` to feed them to `Geometry::get_angle` anymore. Therefore, it may avoid both a useless cast-to-int-then-back-to-double and a potential loss of precision.

Geometry::get_angle now takes double parameters.

---

include/solarus/Camera.h
include/solarus/DialogBoxSystem.h
include/solarus/EquipmentItem.h
include/solarus/entities/Arrow.h
include/solarus/entities/Hero.h
include/solarus/entities/Hookshot.h
include/solarus/entities/Tileset.h
include/solarus/lowlevel/InputEvent.h
include/solarus/lowlevel/Sound.h
include/solarus/lowlevel/shaders/GL_2DShader.h
include/solarus/lowlevel/shaders/GL_ARBShader.h
include/solarus/lowlevel/shaders/Shader.h
include/solarus/lua/LuaContext.h
include/solarus/movements/CircleMovement.h
include/solarus/movements/FallingOnFloorMovement.h
include/solarus/movements/PlayerMovement.h

I ran [flint](https://github.com/facebook/flint) on the code and it wasn't happy because some constructors weren't  `explicit` and may cause sneaky implicit conversions. I added `explicit` and the code still compiles fine.

Made constructors explicit to make lint tools happy.

---

src/TransitionFade.cpp
src/entities/Stairs.cpp

Just two quick fixes proposed by CppCheck, after we talked about what to do with them:
* Reduced the scope of `direction`.
* Initialized `next_frame_date` in `TransitionFade`'s constructor.

Additional CppCheck suggestions.

---

include/solarus/SavegameConverterV1.h
include/solarus/lowlevel/Sound.h
include/solarus/movements/Movement.h
include/solarus/movements/RandomMovement.h
src/lowlevel/Sound.cpp
src/movements/Movement.cpp
src/movements/RandomMovement.cpp

I compiled `flint` from its most recent sources instead of using the old binaries and it found some things that neither its old version nor CppCheck were able to find: two additional constructors that would benefit from being marked `explicit`.
However, I noticed that in some cases, marking `explicit` a constructor that had a default parameter would also make `explicit` either the default constructor or the constructor with two parameters. That's overly restrictive and not really what we want so I tweaked the code so that there are two constructors instead, only the one with one parameter is marked `explicit`, and the one with the least parameters forwards the appropriate values to the one with more parameters.

New flint sources. Fixed overly explicit constructors.

---

src/lua/MapApi.cpp

It seems that MapApi.cpp missed the big range-based `for` loops update a few months ago, so here we go. The only observable difference is that no `EntityPtr` is not copied anymore `map_api_get_entities_in_rectangle`, so it probably saves some reference counting in the underlying `std::shared_ptr`. This time without `auto&&` syntax.

More range-based for loops.

---

src/lua/DrawableApi.cpp

This follows the changes made in an old pull request: use references when possible instead of pointers, even smart ones. It *may* reduce the reference couting since there are less `std::shared_ptr` copies made. I guess (and hope) that the pointer returned by `check_drawable` is guaranteed to point to a valid value and not to delete itself in parallel while we are using the value it points to, otherwise we would expose ourselves to some serious problems.

Use more references instead of std::shared_ptr.

---

cmake/AddInstallTargets.cmake

Should install to the standard '/usr/games/' directory on Debian now.

Changed the install location for Debian.

---

include/solarus/lowlevel/Debug.h
src/lua/LuaContext.cpp
src/lua/TimerApi.cpp

The `NDEBUG` checks begin a bit noisy, I added the function `Debug::execute` to the debugging tools which simply executes a function in debug mode and does nothing otherwise. It allows to wrap in a capturing lambda the code that was in `NDEBUG` guards and feed that lambda to `Debug::execute`, the same way we're already using `LuaTools::exception_boundary_handle`.
I used it directly into two places but didn't modify the third_party libraries that were using it. I hope that it may simplify debug checks without uglifying them too much :)

New function to execute arbitrary code when debugging.

---

.gitignore
cmake/AddCompilationFlags.cmake
include/solarus/Common.h
include/solarus/CurrentQuest.h
include/solarus/Game.h
include/solarus/Map.h
include/solarus/Sprite.h
include/solarus/entities/Detector.h
include/solarus/lowlevel/Color.h
include/solarus/lowlevel/Debug.h
include/solarus/lowlevel/Output.h
src/hero/BowState.cpp

AddCompilationFlags.cmake
this line was giving me trouble:
set_target_properties(SOLARUS_ENGINE PROPERTIES LINK_FLAGS_RELEASE "/SUBSYSTEM:WINDOWS")
Common.h
ignoring some warnings
CurrentQuest.h, Debug.h, Output.h
moved SOLARUS_API (__declspec(dllexport)) to the beginning of the
function declarations where windows likes it.
Detector.h
added SOLARUS_API to class
Game.h, Map.h, Sprite.h, BowState.cpp
Added includes. We were failing a static_assert in
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory
// TEMPLATE CLASS default_delete
template<class _Ty>
struct default_delete
{	// default deleter for unique_ptr
_CONST_FUN default_delete() _NOEXCEPT = default;
template<class _Ty2,
class = typename enable_if<is_convertible<_Ty2 *, _Ty *>::value,
void>::type> …

Changes necessary to compile with MSVC.

---

include/solarus/entities/Npc.h

This patch fixes a linker error I got while trying to build libsolarus_testing with MinGW.

Fix linker error with libsolarus_testing.

---

include/solarus/Map.h
src/Map.cpp

This is a routine change to reduce the code by using more point semantics in `Map::get_ground_from_entity`. It also introduces an overload that takes a `Point` for symmetry in the API and fixes a small typo.

More point semantics for get_ground_from_entity.

---

include/solarus/lowlevel/Debug.h
include/solarus/lowlevel/Rectangle.h
include/solarus/lowlevel/Rectangle.inl

I tried to compile Solarus with MSVC 2015 RTM (using only the C++ build tools, not the whole Visual Studio). I still have to get past the linker stage, but I still managed to get everything that comes before to work. Here are the few changes:
* Change the order of `SOLARUS_API [[noreturn]]`.
* Tweak `Rectangle`'s constructors to bypass a bug in `constexpr`.
* Remove `contexpr` from every other `Rectangle` function. That one was too big to be bypassed.

Fix compilation with MSVC 2015 RTM.

---

cmake/AddInstallTargets.cmake
cmake/modules/FindLuaJit.cmake

This will fix some cmake code:
1. Install library file into lib64 if libsuffix is defined (a common practise)
2. Detect luajit also if it was installed in directory with version suffix e.g. luajit-5_1-2.0
This is needed e.g. on openSUSE Linux (where directories are suffixed with version to allow installation of multiple versions at the same time)

Fix some cmake code

---

src/hero/ForcedWalkingState.cpp

I recently updated CppCheck to the version 1.71 and ran it on Solarus as usual. Not much new things but it managed to find a constructor that could use more constructor initialization list in `ForcedWalkingState`.

Use constructor initialization list (CppCheck 1.71).

---

src/entities/CustomEntity.cpp
src/entities/Entities.cpp
src/entities/TilesetData.cpp
src/lua/MainApi.cpp

New versions of CppCheck, new warnings: remove three unused variables in miscellaneous files, and also declare and initialize a variable later because its original value was always overwritten before being used.

Remove unused variables (CppCheck 1.72)

---

cmake/AddConfigurationHeader.cmake

I changed the cmake config that checked for mkstemp to be more robust. On my system the HAVE_MKSTEMP macro was true because I had Matlab installed, but the function didn't work with my Cygwin MinGW setup.
Now it checks both for linkability (CheckFunctionExists) and presence in the header files (CheckCxxSymbolExists). If both are true then HAVE_MKSTEMP is considered to be true.
Travis build failed probably because cmake is older than 2.8.6.

Fix HAVE_MKSTEMP macro

---

changelog.txt
include/solarus/lowlevel/Video.h
include/solarus/lua/LuaContext.h
src/lowlevel/Video.cpp
src/lua/VideoApi.cpp

Implement the required functionality to poll and manipulate cursor visibility.
Add sol.video.is_cursor_visible() and 
sol.video.set_cursor_visible([cursor_visible]). The former corresponds to
SDL_ShowCursor(-1). The latter corresponds to SDL_ShowCursor(1) when applied
to true, and SDL_ShowCursor(0) when applied to false.
Signed-off-by: Alexander Berntsen <alexander@plaimi.net>

Add cursor visibility functions to the Lua API

---

gui/src/settings.cpp

Overrides QSettings constructor call in Settings class to use
QSettings:SystemScope. Had to hardcode application and organization name to
QSettings constructor.
Closes #948.

Set Solarus Settings to System Scope.

---

gui/CMakeLists.txt
gui/resources/solarus.appdata.xml

My goal is described in https://en.opensuse.org/openSUSE:AppStore but this works across distributions as this is based on the https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps standard.

Added an appdata.xml file for Linux software gallery integration
